// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6eUAxKa7AwhaGFPvtbPSTf3q1eADouE',
    appId: '1:584875089226:web:5a0baa6c68f2cbf92e35b3',
    messagingSenderId: '584875089226',
    projectId: 'recipeapp-eec6c',
    authDomain: 'recipeapp-eec6c.firebaseapp.com',
    storageBucket: 'recipeapp-eec6c.firebasestorage.app',
    measurementId: 'G-GXRJ0FL2B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFi8JV7QKQvnA2qT8zCpM-DnSvLbuf0no',
    appId: '1:584875089226:android:4acfc3bad55195d32e35b3',
    messagingSenderId: '584875089226',
    projectId: 'recipeapp-eec6c',
    storageBucket: 'recipeapp-eec6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx29WaSAiyO4pHzUrIx2bTPKilysdvv2M',
    appId: '1:584875089226:ios:683cf4c15898e3962e35b3',
    messagingSenderId: '584875089226',
    projectId: 'recipeapp-eec6c',
    storageBucket: 'recipeapp-eec6c.firebasestorage.app',
    iosClientId: '584875089226-am72kd6m7nme89mbled5meoif605r35f.apps.googleusercontent.com',
    iosBundleId: 'com.jalam.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx29WaSAiyO4pHzUrIx2bTPKilysdvv2M',
    appId: '1:584875089226:ios:e54e02956a2b98a72e35b3',
    messagingSenderId: '584875089226',
    projectId: 'recipeapp-eec6c',
    storageBucket: 'recipeapp-eec6c.firebasestorage.app',
    iosClientId: '584875089226-29nmhk5bfc1kp0ev1386lqakm1nl4q03.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn6eUAxKa7AwhaGFPvtbPSTf3q1eADouE',
    appId: '1:584875089226:web:ea2f20067175d65a2e35b3',
    messagingSenderId: '584875089226',
    projectId: 'recipeapp-eec6c',
    authDomain: 'recipeapp-eec6c.firebaseapp.com',
    storageBucket: 'recipeapp-eec6c.firebasestorage.app',
    measurementId: 'G-S6N3YKT877',
  );

}